### ISSUE TITLE
All data should be on the main read me file

### ISSUE THREAD

**Issue by dagmawibabi** [fraol0912/awesome-ethiopian-startup-guide#4]
I think instead of having just 5 links on the read me we should show all the data that's added right in front

**Comment by frectonz** [comment]
I think it would be hard to manage when more entries are added.

**Comment by dagmawibabi** [comment]
It would be more appealing and easy to access like

https://github.com/public-apis/public-apis

**Comment by frectonz** [comment]
ok, want we want here is to move the information into the readme file and use the links to link to specific sections of the readme. i will do that

**Comment by frectonz** [comment]
I tried it out and the content became slightly unreadable because the text hierarchy is not well respected if it is all in one file. So I think gathering it into a single file is not necessary. Thank you for your suggestion though

**Comment by dagmawibabi** [comment]
Ohw okay thanks for trying fam
